### PR TITLE
add id

### PR DESCRIPTION
**Pull request by fpermana**
hi Marton Miklos,

This is Indonesian community translation for Sailfish OS. Please let me know if this is worked or not. Thank you.

### CODE REVIEW

**Comment by martonmiklos** [comment]
Hello @fpermana Do you managed to solve the issue mentioned on the TJC?

**Comment by fpermana** [comment]
Not yet. Is it because I used Cygwin on Windows 10?

**Comment by martonmiklos** [comment]
@fpermana 

It might be useful to use the localised name of the language here:
https://github.com/martonmiklos/unofficial-jolla-translation/blob/master/usr/share/jolla-supported-languages/id.conf#L1

I have built an RPM managed to install it. 

Do you want me to publish it on openrepos, or is it going to be included in the SFOS soon?

**Comment by fpermana** [comment]
Hi @martonmiklos,
Thank you for your feedback.
I think it will better to publish it on openrepos first.
About localised name, I don't know localised name of Indonesian language.
Do you know what or where can I find it?

**Comment by martonmiklos** [comment]
@fpermana here you can find the openrepos package:
https://openrepos.net/content/martonmiklos/bahasa-indonesian-community-translation-jolla

The localised name was just a hint. If it is the correct term leave it as it is :)

**Pull request merged**
